name: Deploy

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      BASE_DEPLOY_PATH: /var/www/livewire-wireui.com
      CURRENT_RELEASE_PATH: /var/www/livewire-wireui.com/releases/current

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Release Path
        run: echo "RELEASE_PATH=${{ env.BASE_DEPLOY_PATH }}/releases/$(date +'%s')" >> $GITHUB_ENV

      - name: Upload Release
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          private_key: ${{ secrets.SERVER_PRIVATE_KEY }}
          scp_source: ./*
          scp_target: ${{ env.RELEASE_PATH }}
          before_script: mkdir -p ${{ env.RELEASE_PATH }}
          after_script: |
            cd ${{ env.BASE_DEPLOY_PATH }}/releases
            ls | grep '^[0-9]' | head -n -3 | xargs --no-run-if-empty rm -rf
      - name: Activate Release
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script_stop: true
          script: |
            cp ${{ env.BASE_DEPLOY_PATH }}/.env ${{ env.RELEASE_PATH }}/.env
            cd ${{ env.RELEASE_PATH }}
            composer install --no-ansi --no-dev --no-interaction --no-plugins --no-scripts --prefer-dist --optimize-autoloader
            yarn install --frozen-lockfile
            yarn production
            rm -rf node_modules
            php artisan config:cache
            php artisan route:cache
            php artisan event:cache
            php artisan view:cache
            php artisan migrate --force
            php artisan storage:link --force
            chmod -R 2770 storage bootstrap/cache
            chgrp -R www-data storage bootstrap/cache
            chmod -R ug+rwx storage bootstrap/cache
            ln -nfs ${{ env.RELEASE_PATH }} ${{ env.CURRENT_RELEASE_PATH }}
